#tset_property IOSTANDARD LVCMOS18 [get_ports CP1]
#set_property IOSTANDARD LVCMOS18 [get_ports CP2]
set_property IOSTANDARD LVCMOS18 [get_ports J1]
set_property IOSTANDARD LVCMOS18 [get_ports J2]
set_property IOSTANDARD LVCMOS18 [get_ports K1]
set_property IOSTANDARD LVCMOS18 [get_ports K2]
set_property IOSTANDARD LVCMOS18 [get_ports Q1]
set_property IOSTANDARD LVCMOS18 [get_ports Q2]
set_property IOSTANDARD LVCMOS18 [get_ports Qn1]
set_property IOSTANDARD LVCMOS18 [get_ports Qn2]
set_property IOSTANDARD LVCMOS18 [get_ports R1]
set_property IOSTANDARD LVCMOS18 [get_ports R2]
set_property IOSTANDARD LVCMOS18 [get_ports S1]
set_property IOSTANDARD LVCMOS18 [get_ports S2]
set_property PACKAGE_PIN N17 [get_ports CP1]
set_property PACKAGE_PIN P18 [get_ports CP2]
set_property PACKAGE_PIN V5 [get_ports J1]
set_property PACKAGE_PIN T4 [get_ports K1]
set_property PACKAGE_PIN U6 [get_ports Q1]
set_property PACKAGE_PIN T16 [get_ports Q2]
set_property PACKAGE_PIN R5 [get_ports Qn1]
set_property PACKAGE_PIN V17 [get_ports Qn2]

set_property PACKAGE_PIN V6 [get_ports R1]
set_property PACKAGE_PIN T5 [get_ports S1]
set_property PACKAGE_PIN T6 [get_ports J2]
set_property PACKAGE_PIN V7 [get_ports K2]
set_property PACKAGE_PIN R8 [get_ports R2]
set_property PACKAGE_PIN U9 [get_ports S2]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CP1]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CP2]

set_property PACKAGE_PIN E3 [get_ports CP]
set_property IOSTANDARD LVCMOS18 [get_ports CP]
set_property PACKAGE_PIN N17 [get_ports reset1]
set_property PACKAGE_PIN P18 [get_ports reset2]
set_property IOSTANDARD LVCMOS18 [get_ports reset2]
set_property IOSTANDARD LVCMOS18 [get_ports reset1]

set_property IOSTANDARD LVCMOS18 [get_ports CP1]
set_property IOSTANDARD LVCMOS18 [get_ports CP2]
set_property PACKAGE_PIN U18 [get_ports reset1]
set_property PACKAGE_PIN U17 [get_ports reset2]
