# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/Project/Exp8/Exp8.srcs/sources_1/ip/RAM_Data/RAM_Data.xci
# IP: The module: 'RAM_Data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Project/Exp8/Exp8.srcs/sources_1/ip/RAM_Data/RAM_Data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_Data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Documents/Project/Exp8/Exp8.srcs/sources_1/ip/RAM_Data/RAM_Data.xci
# IP: The module: 'RAM_Data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Project/Exp8/Exp8.srcs/sources_1/ip/RAM_Data/RAM_Data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_Data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
