# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Desktop/10_final/10_final/10_final.srcs/sources_1/ip/RAM_I/RAM_I.xci
# IP: The module: 'RAM_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/10_final/10_final/10_final.srcs/sources_1/ip/RAM_I/RAM_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_I'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Desktop/10_final/10_final/10_final.srcs/sources_1/ip/RAM_I/RAM_I.xci
# IP: The module: 'RAM_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/10_final/10_final/10_final.srcs/sources_1/ip/RAM_I/RAM_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_I'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
