# 开启比特流压缩，优化bit文件大小
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

# 32位开关的引脚约束，下拉
set_property PULLDOWN true [get_ports {in[31]}]
set_property PULLDOWN true [get_ports {in[30]}]
set_property PULLDOWN true [get_ports {in[29]}]
set_property PULLDOWN true [get_ports {in[28]}]
set_property PULLDOWN true [get_ports {in[27]}]
set_property PULLDOWN true [get_ports {in[26]}]
set_property PULLDOWN true [get_ports {in[25]}]
set_property PULLDOWN true [get_ports {in[24]}]
set_property PULLDOWN true [get_ports {in[23]}]
set_property PULLDOWN true [get_ports {in[22]}]
set_property PULLDOWN true [get_ports {in[21]}]
set_property PULLDOWN true [get_ports {in[20]}]
set_property PULLDOWN true [get_ports {in[19]}]
set_property PULLDOWN true [get_ports {in[18]}]
set_property PULLDOWN true [get_ports {in[17]}]
set_property PULLDOWN true [get_ports {in[16]}]
set_property PULLDOWN true [get_ports {in[15]}]
set_property PULLDOWN true [get_ports {in[14]}]
set_property PULLDOWN true [get_ports {in[13]}]
set_property PULLDOWN true [get_ports {in[12]}]
set_property PULLDOWN true [get_ports {in[11]}]
set_property PULLDOWN true [get_ports {in[10]}]
set_property PULLDOWN true [get_ports {in[9]}]
set_property PULLDOWN true [get_ports {in[8]}]
set_property PULLDOWN true [get_ports {in[7]}]
set_property PULLDOWN true [get_ports {in[6]}]
set_property PULLDOWN true [get_ports {in[5]}]
set_property PULLDOWN true [get_ports {in[4]}]
set_property PULLDOWN true [get_ports {in[3]}]
set_property PULLDOWN true [get_ports {in[2]}]
set_property PULLDOWN true [get_ports {in[1]}]
set_property PULLDOWN true [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in[0]}]
set_property PACKAGE_PIN T3 [get_ports {in[31]}]
set_property PACKAGE_PIN U3 [get_ports {in[30]}]
set_property PACKAGE_PIN T4 [get_ports {in[29]}]
set_property PACKAGE_PIN V3 [get_ports {in[28]}]
set_property PACKAGE_PIN V4 [get_ports {in[27]}]
set_property PACKAGE_PIN W4 [get_ports {in[26]}]
set_property PACKAGE_PIN Y4 [get_ports {in[25]}]
set_property PACKAGE_PIN Y6 [get_ports {in[24]}]
set_property PACKAGE_PIN W7 [get_ports {in[23]}]
set_property PACKAGE_PIN Y8 [get_ports {in[22]}]
set_property PACKAGE_PIN Y7 [get_ports {in[21]}]
set_property PACKAGE_PIN T1 [get_ports {in[20]}]
set_property PACKAGE_PIN U1 [get_ports {in[19]}]
set_property PACKAGE_PIN U2 [get_ports {in[18]}]
set_property PACKAGE_PIN W1 [get_ports {in[17]}]
set_property PACKAGE_PIN W2 [get_ports {in[16]}]
set_property PACKAGE_PIN Y1 [get_ports {in[15]}]
set_property PACKAGE_PIN AA1 [get_ports {in[14]}]
set_property PACKAGE_PIN V2 [get_ports {in[13]}]
set_property PACKAGE_PIN Y2 [get_ports {in[12]}]
set_property PACKAGE_PIN AB1 [get_ports {in[11]}]
set_property PACKAGE_PIN AB2 [get_ports {in[10]}]
set_property PACKAGE_PIN AB3 [get_ports {in[9]}]
set_property PACKAGE_PIN AB5 [get_ports {in[8]}]
set_property PACKAGE_PIN AA6 [get_ports {in[7]}]
set_property PACKAGE_PIN R2 [get_ports {in[6]}]
set_property PACKAGE_PIN R3 [get_ports {in[5]}]
set_property PACKAGE_PIN T6 [get_ports {in[4]}]
set_property PACKAGE_PIN R6 [get_ports {in[3]}]
set_property PACKAGE_PIN U7 [get_ports {in[2]}]
set_property PACKAGE_PIN AB7 [get_ports {in[1]}]
set_property PACKAGE_PIN AB8 [get_ports {in[0]}]



# 数码管的段选引脚约束
set_property IOSTANDARD LVCMOS18 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[0]}]
set_property PACKAGE_PIN H19 [get_ports {seg[7]}]
set_property PACKAGE_PIN G20 [get_ports {seg[6]}]
set_property PACKAGE_PIN J22 [get_ports {seg[5]}]
set_property PACKAGE_PIN K22 [get_ports {seg[4]}]
set_property PACKAGE_PIN K21 [get_ports {seg[3]}]
set_property PACKAGE_PIN H20 [get_ports {seg[2]}]
set_property PACKAGE_PIN H22 [get_ports {seg[1]}]
set_property PACKAGE_PIN J21 [get_ports {seg[0]}]
# 数码管的位选及使能信号的约束
set_property IOSTANDARD LVCMOS18 [get_ports {which[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {which[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {which[0]}]
set_property PACKAGE_PIN N22 [get_ports {which[0]}]
set_property PACKAGE_PIN M21 [get_ports {which[1]}]
set_property PACKAGE_PIN M22 [get_ports {which[2]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN L21} [get_ports enable]

#时钟源20MHz
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN H4} [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_IBUF}]
# [Place 30-574] Poor placement for routing between an IO pin and BUFG.If this
# sub optimal condition is acceptable for this design, you may use the
# CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a
# WARNING. However, the use of this override is highly discouraged.
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_B_IBUF}]

set_property IOSTANDARD LVCMOS18 [get_ports {Flags[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Flags[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Flags[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Flags[0]}]
set_property PACKAGE_PIN R1 [get_ports {Flags[3]}]
set_property PACKAGE_PIN P2 [get_ports {Flags[2]}]
set_property PACKAGE_PIN P1 [get_ports {Flags[1]}]
set_property PACKAGE_PIN N2 [get_ports {Flags[0]}]
set_property PACKAGE_PIN R4 [get_ports clk_A]
set_property PACKAGE_PIN AA4 [get_ports clk_B]
set_property PACKAGE_PIN AB6 [get_ports clk_F]
set_property PACKAGE_PIN V8 [get_ports rst]
set_property PACKAGE_PIN AA8 [get_ports rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports clk_A]
set_property IOSTANDARD LVCMOS18 [get_ports clk_B]
set_property IOSTANDARD LVCMOS18 [get_ports clk_F]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
