# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Documents/Project/Exp10/Exp10.cache/wt [current_project]
set_property parent.project_path D:/Documents/Project/Exp10/Exp10.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Documents/Project/Exp10/Exp10.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Documents/Project/Exp8/Exp8.srcs/sources_1/ip/init.coe
add_files D:/Documents/Project/Exp10/Exp8.coe
add_files D:/Documents/Project/Exp10/Exp10.coe
add_files d:/Documents/Project/Exp10/init.coe
read_verilog -library xil_defaultlib {
  D:/Documents/Project/Exp3/Exp3.srcs/sources_1/new/ALU.v
  D:/Documents/Project/Board_Test/Board_Test/Board_Test.srcs/sources_1/new/Display.v
  D:/Documents/Project/Exp7/Exp7.srcs/sources_1/new/ID1.v
  D:/Documents/Project/Exp7/Exp7.srcs/sources_1/new/IR.v
  D:/Documents/Project/Exp8/Exp8.srcs/sources_1/new/PC0.v
  D:/Documents/Project/Exp8/Exp8.srcs/sources_1/new/PC_select.v
  D:/Documents/Project/Exp7/Exp7.srcs/sources_1/new/adder.v
  D:/Documents/Project/Exp8/Exp8.srcs/sources_1/new/cu.v
  D:/Documents/Project/Exp7/Exp7.srcs/sources_1/new/exp7_top.v
  D:/Documents/Project/Exp8/Exp8.srcs/sources_1/new/id2.v
  D:/Documents/Project/Exp7/Exp7.srcs/sources_1/new/pc_reg.v
  D:/Documents/Project/Exp8/Exp8.srcs/sources_1/new/register_32.v
  D:/Documents/Project/Exp4/Exp4.srcs/sources_1/new/register_heap.v
  D:/Documents/Project/Exp8/Exp8.srcs/sources_1/new/rs2_imm_select.v
  D:/Documents/Project/Exp10/Exp10.srcs/sources_1/new/top_2.v
  D:/Documents/Project/Exp8/Exp8.srcs/sources_1/new/w_data_select.v
  D:/Documents/Project/Exp8/Exp8.srcs/sources_1/new/Top.v
}
read_ip -quiet D:/Documents/Project/Exp10/Exp10.srcs/sources_1/ip/IM/IM.xci
set_property used_in_implementation false [get_files -all d:/Documents/Project/Exp10/Exp10.srcs/sources_1/ip/IM/IM_ooc.xdc]

read_ip -quiet D:/Documents/Project/Exp10/Exp10.srcs/sources_1/ip/RAM_Data/RAM_Data.xci
set_property used_in_implementation false [get_files -all d:/Documents/Project/Exp10/Exp10.srcs/sources_1/ip/RAM_Data/RAM_Data_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Documents/Project/Exp8/Exp8.srcs/constrs_1/new/Top.xdc
set_property used_in_implementation false [get_files D:/Documents/Project/Exp8/Exp8.srcs/constrs_1/new/Top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tfgg484-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
